# Generated by Django 5.1.4 on 2024-12-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
    ]
